### ISSUE TITLE
Mapping volumes to host directories fails

### ISSUE THREAD

**Issue by wilreichert** [cptactionhank/docker-atlassian-jira#22]
The following fails to work

```
docker run --rm -p 8080:8080 \
  -v /var/atlassian/jira:/var/atlassian/jira \
  -v /opt/atlassian/jira:/opt/atlassian/jira \
  cptactionhank/atlassian-jira:latest
```

Using a docker volume copies the existing data into the volume.  Mapping to a directory behaves like a normal unix mount and the existing data is not copied.

Looking at the Dockerfile there is not really an obvious solution.  A bit of setup would need to be moved to the first time the container was started perhaps.

**Comment by cptactionhank** [comment]
I'm not really sure as to why you would mount the installation folder, could you elaborate further on that? It does make sense that the container won't start its process based on how volume mounting works and I'm not really sure about the motivation of doing this would be.

If you instead would do the following
```
docker run --rm -p 8080:8080 \
  -v /var/atlassian/jira:/var/atlassian/jira \
  -v /opt/atlassian/jira \
  cptactionhank/atlassian-jira:latest
```
the container will once again be able to start and the installation folder will be persisted even after the container has been restarted, as when eg. Docker Engine restarts or the physical container host restarts.

Are you using add-ons that changes files in the installation directory, since you might have this requirement?

**Comment by wilreichert** [comment]
Ah, you are correct - I only need to setup persistent storage for the home directory.  Anything that needs persisting across containers beyond install logs in /opt/atlassian//jira?

Thanks for the reply.

**Comment by cptactionhank** [comment]
I don't believe so, maybe if using some special ill behaving add-on do modifications to the install directory. However to my knowledge it should not be necessary to mount the install directory and I will specify the log directory as a volume as well in the `Dockerfile`, if not already added. This way all the important data is persistent through the containers lifetime.

External mounting of the home folder is not strictly necessary for a persistent running container instance. It is however the way I have been running my instances, but with the newer versions of Docker Engine I would likely switch to create external volume mounts with `docker volume create`.

Kind regards,

Martin Jensen
