### ISSUE TITLE
dockerhub readme corrupted

### ISSUE THREAD

**Issue by pgleghorn** [cptactionhank/docker-atlassian-jira#36]
Thanks for this excellent project.
Not reporting a code issue, but the documentation on dockerhub seems to be corrupted, see
https://cptactionhank.github.io/docker-atlassian-jira/#configuring-system-properties

**Comment by Mansarde** [comment]
I think that's just placeholder-text, kind of like "Lorep Ipsum..." etc.

**Comment by cptactionhank** [comment]
It is indeed various lorem ipsum generated text and a mistake on my part. Because of a conflict of interests with my workplace I cannot improve on this since it kind of competes with some of the services it provides. So instead of removing the whole site I left it semi-working and with confusing mumble text, sorry about this.

**Comment by pgleghorn** [comment]
makes sense, thanks again :)
