### ISSUE TITLE
Ability to link database container

### ISSUE THREAD

**Issue by soupdiver** [cptactionhank/docker-atlassian-jira#5]
Have you thought about adding the possibility to link a database container?
Otherwise I had to get the IP of the database container manually and add during the setup process of JIRA. Also when the IP of the database changes I had to manually reconfigure JIRA.
See: https://bitbucket.org/atlassianlabs/atlassian-docker/src/9da1818bd2415d8cf7da4b354151cd6ad42b0f92/jira/launch.bash?at=master

What do you think about this?

**Comment by cptactionhank** [comment]
Awesome! I wasn't aware that you could pre-configure the database settings. I have been using container linking without the need for manually finding and managing IP's by using the hostname alias docker creates when linking a container. The HOSTS file get updated with the linked containers ip and alias. But I can see the convenience in all this being auto configured when possible.

I'd like to look more into this, do you have a link for JIRA documentation about this and idea's for defaults eg. default database name could be assumed `jiradb` etc.

**Comment by soupdiver** [comment]
Documentation can be found here: https://confluence.atlassian.com/display/JIRA/Connecting+JIRA+to+a+Database

I'm not sure about defaults because this depends on the setup of the database container.

An idea would be to only write the `server.xml` if **all** required db settings are given. Otherwise just skip and the wizard will come up, like in the script I linked to.

It's a bit annoying that it is so complicated to extract the right values and put them in the xml file but it seems there is no way around.

**Comment by cptactionhank** [comment]
True, the less work the better right ;) I will look into this as soon as I can.

**Comment by cptactionhank** [comment]
Update: I still haven't forgotten this proposal and I'm working towards getting this implemented. I just need to refine and improve the integration tests first such that further improvements and changes can be tested not to break stuff.

**Comment by griff** [comment]
As the guy who wrote that code I can say that it is only complicated because it is written as bash code. It is MUCH simpler in ANY language that that can parse an URL. The url parsing code actually also has [tests](https://github.com/griff/dokdb/blob/master/tests/common/test_url.sh) since I just took it from some experiments I was doing with auto-configuring database connections using only docker links.

**Comment by soupdiver** [comment]
Yeah I also realised that it is not trivial to do this with only bash

**Comment by cptactionhank** [comment]
So I have been wanting to do this initially because I think it is a good idea, and still is, but I have chosen not to do this, to minimize the maintenance burden and to keep the images as vanilla as possible. It is still easy to do linking and setting up a database and it's true it would be easier if it were done automagically, however it is a one-off thing that shouldn't be done that often and thus I have decided to leave this out.
