### ISSUE TITLE
JIRA couldn't create the jira.home directory

### ISSUE THREAD

**Issue by webncut** [cptactionhank/docker-atlassian-jira#53]
If any folder ist mounted on Synology Docker I got the error.
Setup: JIRA couldn't create the jira.home directory
Ensure JIRA has permission to create and write to the jira.home directory /var/atlassian/jira.
Review our documentation for more information on setting your JIRA home.
Learn more
![jira error](https://user-images.githubusercontent.com/21197742/31197026-0cfd3588-a950-11e7-9c71-836c0aff4475.PNG)

**Comment by dbeuchler** [comment]
Same issue here - changed the volume: ` --volume /home/docker/jira:/var/atlassian/jira`

**Comment by jkblume** [comment]
Same issue here - how do you solve this?!

**Comment by cros91** [comment]
Hey there,

i propably fixxed this and now there is no error warning any more, but i am not sure if there will be another error later on.

My Path ist /docker/jira and i will mount it on /var/atlassian/jira so i did the following:

Go to your file station
Right Click on the "docker" folder
Click "Properties"
Now there must be a tab called "Permission" or something similar (i use this in german)
Finally, you have to change the Permissions of Group "Everyone" so that this Group is able to write too.

Restart the JIRA Docker Container and now the JIRA Setup will start correctly :)

Hope this will help you :)

**Comment by scott8035** [comment]
Wait a second...creating a wide-open directory is not an acceptable fix for a production application. I have mine mapped like:

```
    --volume "/var/atlassian/application-data/jira:/var/atlassian/jira"
```
 and there's no way I'm going to ```chmod 777 /var/atlassian/application-data/jira```. Is there a better way to resolve this?

**Comment by WiedemannD** [comment]
Same issue here.

> Why not just `chown` with the daemon user (uid 2) instead of `chmod`?

This made my updated Jira container work again. But does giving daemon ownership of the folders open up security issues? Sorry, I'm very unsure of what daemon really does and how it works.

Thanks in advance!
